name: maverickpigao_portfolio_cs3
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  url_launcher: ^6.0.20

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Wix Regular
      fonts:
        - asset: fonts/WixMadeforDisplayRegular.otf

    - family: Wix Bold
      fonts:
        - asset: fonts/WixMadeforDisplayBold.otf

    - family: Wix ExtraBold
      fonts:
        - asset: fonts/WixMadeforDisplayExtraBold.otf
